### PR TITLE
feat(alpenhorn): small-file diversions

### PR DESCRIPTION
**Pull request by ketiltrout**
(This is why I started complaining about groups...)

This adds support for diverting small files somewhere else when `sync`ing files from a node to a group.  Changes are client-only.

Two new columns have been added to `StorageGroup` (see https://github.com/chime-experiment/chimedb_di/pull/13) :
* `small_group`: a self-referential foreign key to another StorageGroup used to store small files
* `small_size`: the threshold (in bytes) for small files.

When a `sync` is made to a `StorageGroup` which has a `small_group` defined, the client will generate `ArchiveFileCopyRequest`s which send large files to the primary group and files below the defined small-file threshold to the specified small-file `StorageGroup`.  

Also:
* added a new command: `alpenhorn smallfile` which can find and clean-up misplaced or duplicated files in a group with an associated small-file group.
* removed the `--transport` option from `alpenhorn sync`, which has been marked deprecated for a long time
* removed the `--nice` option from `alpenhorn sync`, which has never been honoured.
  * (There's a `nice` column in `ArchiveFileCopyRequest`, and value passed to `--nice` would be recorded then when `sync` updated existing requests, but new requests always had `nice` set to zero.  The `alpenhornd` daemon ignores the `nice` column.)
* added a `--no-delegation` option to `alpenhorn sync`, which prevents it from diverting small files to a small-file group (i.e. all transfers will go to the group specified, even if they're smaller than the threshold).

Other notes:
 * The `alpenhorn smallfile` command is written with the assumption that there's probably only one node in a group.  It will work regardless, but not efficiently.
 * Running `alpenhorn sync` targetting the small-file group directly won't result in large files being sent somewhere else: everything will end up in the group specified.
 * When using the parent group as a `--target`, `alpenhorn` will behave as if the files in an associated small-file group are also part of the --target.  Similarly, attempting to sync a file already present in a small-file group to the parent group will do nothing.  (The intention being that users should have to care whether a file has been diverted to a small-file group or not.)

No changes to `alpenhornd`.

Also, added some unittests which seem to need a bug fixed in `chimedb.core` to work reliably. See: https://github.com/chime-experiment/chimedb/pull/21

### CODE REVIEW

**Comment by jrs65** [comment]
These changes are quite invasive, and I'm not sure why they need to be.

I had envisaged this could be done very easily by putting a size filter on the sync command, and then running two sync commands like:
```
alpenhorn sync --size-max 1G cedar_staging cedar_smallfiles
alpenhorn sync --size-min 1G cedar_staging cedar_archive
```
and that involves no particularly invasive changes to the table model. Is there a reason I'm missing that something like this wouldn't work?

I do like the elegance of this though, but I'm concerned about adding too much complexity in the core for a fairly niche thing.

**Comment by jrs65** [comment]
I mean it looks like your implementation basically does this anyway, i.e. all the changes are in the client code. If that's true, it seems like all the changes to the database schema are just to avoid passing some command line arguments. To me that doesn't seem worth it.

It could be worth it if was the server code that was figuring out which node/group to dispatch to and enforcing the limits directly.

**Comment by ketiltrout** [comment]
I think it's better to have the config in the database.  That's were we store the rest of the config.  It prevents us from screwing things up by forgetting to include the limit on the command line.

**Comment by jrs65** [comment]
> I think it's better to have the config in the database. That's were we store the rest of the config. It prevents us from screwing things up by forgetting to include the limit on the command line.

It's not really though. Much of the "config" is essentially defined in a cron job. I don't really see how this is fundamentally that different, we're just telling it how to move data from one location to another with an extra selection function.

How about an alternative implementation where you give the StorageNodes max and min file size limits? Then the daemon decides which node to transfer to out of those nodes in a group based on the limits (i.e. it picks the first satisfying all constraints, at the moment the constraints are has enough space and is mounted, so this would add one more). In this mode the cedar_nearline and cedar_smallfiles nodes would exist in the same group, and the nodes would have mutually exclusive size limits. I think this is preferable as it fits in better with the current way nodes/groups work, and it moves the enforcement of the size limits to the daemon rather than the client.

**Comment by ketiltrout** [comment]
Sure.  We can give that a go.

**Comment by ketiltrout** [comment]
Moved to alpenhorn-2: https://github.com/radiocosmology/alpenhorn/pull/156

**Pull request closed without merging**
